/**
 * Realistic fake books of a Hungarian home library (owner: ui-kit).
 * Used by the /ui-preview style guide and handy for tests / stories of other UI modules.
 * Pure data – safe on server and client.
 */
import type { BookDTO } from '@/lib/types';

let seq = 0;

/** Builds a complete BookDTO from a few fields (sensible defaults for everything else). */
export function makeSampleBook(partial: Partial<BookDTO> & { title: string }): BookDTO {
  seq += 1;
  const n = seq;
  const created = new Date(Date.UTC(2026, 8, 1, 10, 0, 0) + n * 3_600_000).toISOString();
  return {
    id: `sample-${String(n).padStart(3, '0')}`,
    subtitle: null,
    author: null,
    spineAuthor: partial.author ?? null,
    spineTitle: partial.title,
    authorSort: null,
    titleSort: null,
    originalTitle: null,
    series: null,
    publisher: null,
    language: 'hu',
    originalLanguage: null,
    authorCountry: null,
    firstPublishedYear: null,
    editionYear: null,
    isbn: null,
    pageCount: null,
    category: null,
    topics: [],
    tags: [],
    descriptionHu: null,
    descriptionEn: null,
    coverImage: null,
    coverFromOriginalEdition: false,
    spineImage: null,
    spineColor: null,
    source: 'video',
    confidence: 0.92,
    needsReview: false,
    reviewed: false,
    bestFrameId: null,
    bestBbox: null,
    firstVideoId: null,
    firstTimeSec: n * 0.4,
    shelfPosition: n,
    detectionCount: 3,
    readingStatus: 'unknown',
    rating: null,
    favorite: false,
    notes: null,
    lentTo: null,
    lentAt: null,
    enriched: true,
    createdAt: created,
    updatedAt: created,
    ...partial,
  };
}

type Seed = Partial<BookDTO> & { title: string };

const seeds: Seed[] = [
  {
    author: 'Szabó Magda',
    authorSort: 'szabo magda',
    title: 'Az ajtó',
    firstPublishedYear: 1987,
    pageCount: 256,
    category: 'hungarian_literature',
    topics: ['literary_fiction'],
    authorCountry: 'HU',
    publisher: 'Európa',
    readingStatus: 'read',
    rating: 5,
    favorite: true,
    spineColor: '#7b2d26',
    descriptionHu: 'Egy írónő és különös házvezetőnője, Szeredás Emerenc évtizedes, feszült kapcsolatának története.',
    descriptionEn: 'A writer and her enigmatic housekeeper, Emerenc, bound by decades of fierce, fragile trust.',
  },
  {
    author: 'Esterházy Péter',
    authorSort: 'esterhazy peter',
    title: 'Harmonia Caelestis',
    firstPublishedYear: 2000,
    pageCount: 720,
    category: 'hungarian_literature',
    authorCountry: 'HU',
    publisher: 'Magvető',
    readingStatus: 'reading',
    spineColor: '#e9e1cf',
  },
  {
    author: 'Kertész Imre',
    authorSort: 'kertesz imre',
    title: 'Sorstalanság',
    firstPublishedYear: 1975,
    pageCount: 330,
    category: 'hungarian_literature',
    topics: ['historical_fiction'],
    authorCountry: 'HU',
    publisher: 'Magvető',
    readingStatus: 'read',
    rating: 4,
  },
  {
    author: 'Molnár Ferenc',
    authorSort: 'molnar ferenc',
    title: 'A Pál utcai fiúk',
    firstPublishedYear: 1906,
    pageCount: 196,
    category: 'young_adult',
    topics: ['classics', 'hungarian_literature'],
    authorCountry: 'HU',
    publisher: 'Móra',
    readingStatus: 'read',
    rating: 5,
    spineColor: '#2c5a3f',
  },
  {
    author: 'Jókai Mór',
    authorSort: 'jokai mor',
    title: 'Az arany ember',
    firstPublishedYear: 1872,
    pageCount: 540,
    category: 'classics',
    topics: ['hungarian_literature'],
    authorCountry: 'HU',
    readingStatus: 'to_read',
  },
  {
    author: 'Örkény István',
    authorSort: 'orkeny istvan',
    title: 'Egyperces novellák',
    firstPublishedYear: 1968,
    pageCount: 280,
    category: 'short_stories',
    topics: ['humor', 'hungarian_literature'],
    authorCountry: 'HU',
    publisher: 'Palatinus',
    rating: 4,
    spineColor: '#d8a53a',
  },
  {
    author: 'Karinthy Frigyes',
    authorSort: 'karinthy frigyes',
    title: 'Így írtok ti',
    firstPublishedYear: 1912,
    pageCount: 420,
    category: 'humor',
    authorCountry: 'HU',
  },
  {
    author: 'Rejtő Jenő',
    authorSort: 'rejto jeno',
    title: 'A tizennégy karátos autó',
    firstPublishedYear: 1940,
    pageCount: 230,
    category: 'humor',
    topics: ['crime_thriller'],
    authorCountry: 'HU',
    readingStatus: 'read',
    rating: 5,
    favorite: true,
    lentTo: 'Bence',
    lentAt: '2026-08-20',
  },
  {
    author: 'Márai Sándor',
    authorSort: 'marai sandor',
    title: 'A gyertyák csonkig égnek',
    firstPublishedYear: 1942,
    pageCount: 214,
    category: 'hungarian_literature',
    authorCountry: 'HU',
    publisher: 'Helikon',
    spineColor: '#1b2a3a',
  },
  {
    author: 'Krasznahorkai László',
    authorSort: 'krasznahorkai laszlo',
    title: 'Sátántangó',
    firstPublishedYear: 1985,
    pageCount: 312,
    category: 'literary_fiction',
    authorCountry: 'HU',
    readingStatus: 'abandoned',
    rating: 2,
  },
  {
    author: 'Nádas Péter',
    authorSort: 'nadas peter',
    title: 'Párhuzamos történetek',
    firstPublishedYear: 2005,
    pageCount: 1500,
    category: 'literary_fiction',
    authorCountry: 'HU',
    publisher: 'Jelenkor',
    readingStatus: 'to_read',
    spineColor: '#f1ede4',
  },
  {
    author: 'Gárdonyi Géza',
    authorSort: 'gardonyi geza',
    title: 'Egri csillagok',
    firstPublishedYear: 1899,
    pageCount: 620,
    category: 'historical_fiction',
    topics: ['classics', 'young_adult'],
    authorCountry: 'HU',
    readingStatus: 'read',
    rating: 4,
    spineColor: '#8c2f2a',
  },
  {
    author: 'Weöres Sándor',
    authorSort: 'weores sandor',
    title: 'Bóbita',
    firstPublishedYear: 1955,
    pageCount: 64,
    category: 'children',
    topics: ['poetry'],
    authorCountry: 'HU',
    spineColor: '#e5b94c',
  },
  {
    author: 'Fekete István',
    authorSort: 'fekete istvan',
    title: 'Vuk',
    firstPublishedYear: 1965,
    pageCount: 150,
    category: 'children',
    topics: ['nature'],
    authorCountry: 'HU',
    readingStatus: 'read',
  },
  {
    author: 'Elena Ferrante',
    authorSort: 'ferrante elena',
    title: 'Briliáns barátnőm',
    originalTitle: "L'amica geniale",
    originalLanguage: 'it',
    firstPublishedYear: 2011,
    pageCount: 390,
    category: 'literary_fiction',
    authorCountry: 'IT',
    series: 'Nápolyi regények',
    publisher: 'Park',
    readingStatus: 'reading',
  },
  {
    author: 'J. R. R. Tolkien',
    authorSort: 'tolkien j r r',
    title: 'A Gyűrűk Ura',
    originalTitle: 'The Lord of the Rings',
    originalLanguage: 'en',
    firstPublishedYear: 1954,
    pageCount: 1250,
    category: 'fantasy',
    topics: ['classics'],
    authorCountry: 'GB',
    publisher: 'Európa',
    isbn: '9780261103252',
    coverImage: 'https://covers.openlibrary.org/b/isbn/9780261103252-L.jpg?default=false',
    readingStatus: 'read',
    rating: 5,
    favorite: true,
    spineColor: '#20242a',
  },
  {
    author: 'George Orwell',
    authorSort: 'orwell george',
    title: '1984',
    originalTitle: 'Nineteen Eighty-Four',
    originalLanguage: 'en',
    firstPublishedYear: 1949,
    pageCount: 340,
    category: 'scifi',
    topics: ['classics', 'society_politics'],
    authorCountry: 'GB',
    publisher: 'Európa',
    readingStatus: 'read',
    rating: 5,
  },
  {
    author: 'Yuval Noah Harari',
    authorSort: 'harari yuval noah',
    title: 'Sapiens – Az emberiség rövid története',
    originalTitle: 'Sapiens: A Brief History of Humankind',
    originalLanguage: 'he',
    firstPublishedYear: 2011,
    pageCount: 520,
    category: 'history',
    topics: ['science'],
    authorCountry: 'IL',
    publisher: 'Animus',
    readingStatus: 'to_read',
    spineColor: '#f2f0ea',
  },
  {
    author: 'Daniel Kahneman',
    authorSort: 'kahneman daniel',
    title: 'Gyors és lassú gondolkodás',
    originalLanguage: 'en',
    firstPublishedYear: 2011,
    pageCount: 560,
    category: 'psychology',
    authorCountry: 'US',
    publisher: 'HVG Könyvek',
  },
  {
    author: 'Agatha Christie',
    authorSort: 'christie agatha',
    title: 'Gyilkosság az Orient expresszen',
    originalLanguage: 'en',
    firstPublishedYear: 1934,
    pageCount: 256,
    category: 'crime_thriller',
    authorCountry: 'GB',
    readingStatus: 'read',
    rating: 3,
  },
  {
    author: 'Gabriel García Márquez',
    authorSort: 'garcia marquez gabriel',
    title: 'Száz év magány',
    originalTitle: 'Cien años de soledad',
    originalLanguage: 'es',
    firstPublishedYear: 1967,
    pageCount: 470,
    category: 'literary_fiction',
    topics: ['classics'],
    authorCountry: 'CO',
    spineColor: '#c4632f',
  },
  {
    author: 'Mihail Bulgakov',
    authorSort: 'bulgakov mihail',
    title: 'A Mester és Margarita',
    originalLanguage: 'ru',
    firstPublishedYear: 1967,
    pageCount: 480,
    category: 'classics',
    topics: ['fantasy'],
    authorCountry: 'RU',
    readingStatus: 'reading',
  },
  {
    author: 'Umberto Eco',
    authorSort: 'eco umberto',
    title: 'A rózsa neve',
    originalTitle: 'Il nome della rosa',
    originalLanguage: 'it',
    firstPublishedYear: 1980,
    pageCount: 600,
    category: 'historical_fiction',
    topics: ['crime_thriller'],
    authorCountry: 'IT',
    spineColor: '#3b2a4a',
  },
  {
    author: 'Arany János',
    authorSort: 'arany janos',
    title: 'Toldi',
    firstPublishedYear: 1846,
    pageCount: 120,
    category: 'poetry',
    topics: ['classics', 'hungarian_literature'],
    authorCountry: 'HU',
  },
  {
    author: 'Bánffy Miklós',
    authorSort: 'banffy miklos',
    title: 'Erdélyi történet',
    firstPublishedYear: 1934,
    pageCount: 1400,
    category: 'historical_fiction',
    authorCountry: 'HU',
    spineColor: '#1d3b2e',
  },
  {
    author: 'Szerb Antal',
    authorSort: 'szerb antal',
    title: 'Utas és holdvilág',
    firstPublishedYear: 1937,
    pageCount: 290,
    category: 'hungarian_literature',
    authorCountry: 'HU',
    readingStatus: 'read',
    rating: 5,
  },
  {
    author: 'Csáth Géza',
    authorSort: 'csath geza',
    title: 'A varázsló kertje',
    firstPublishedYear: 1908,
    pageCount: 180,
    category: 'short_stories',
    authorCountry: 'HU',
  },
  {
    author: 'Dzsida Jenő',
    authorSort: 'dzsida jeno',
    title: 'Hálaadás',
    firstPublishedYear: 1938,
    pageCount: 96,
    category: 'poetry',
    authorCountry: 'RO',
    spineColor: '#4d6a92',
  },
  {
    author: 'Stefan Zweig',
    authorSort: 'zweig stefan',
    title: 'Sakknovella',
    originalTitle: 'Schachnovelle',
    originalLanguage: 'de',
    firstPublishedYear: 1942,
    pageCount: 110,
    category: 'short_stories',
    authorCountry: 'AT',
  },
  {
    author: 'Jonas Jonasson',
    authorSort: 'jonasson jonas',
    title: 'A százéves ember, aki kimászott az ablakon és eltűnt',
    originalLanguage: 'sv',
    firstPublishedYear: 2009,
    pageCount: 400,
    category: 'humor',
    authorCountry: 'SE',
    readingStatus: 'to_read',
    spineColor: '#e9c46a',
  },
  {
    author: 'Lyka Károly',
    authorSort: 'lyka karoly',
    title: 'Magyar művészet 1800–1850',
    firstPublishedYear: 1942,
    pageCount: 260,
    category: 'art',
    topics: ['history'],
    authorCountry: 'HU',
  },
  {
    author: null,
    title: 'Magyar–angol kéziszótár',
    publisher: 'Akadémiai Kiadó',
    pageCount: 1100,
    category: 'reference',
    topics: ['language_learning'],
    confidence: 0.54,
    needsReview: true,
    source: 'video',
    spineColor: '#0f4c81',
  },
  {
    author: 'Gyurkovics Tibor',
    authorSort: 'gyurkovics tibor',
    title: 'Mengele bolond szerelme',
    firstPublishedYear: 2000,
    confidence: 0.41,
    needsReview: true,
    spineTitle: 'Mengele bol',
    category: 'literary_fiction',
    authorCountry: 'HU',
    coverImage: 'https://covers.openlibrary.org/b/id/0-L.jpg?default=false',
  },
  {
    author: 'Nemes Nagy Ágnes',
    authorSort: 'nemes nagy agnes',
    title: 'Szó és szótlanság',
    firstPublishedYear: 1989,
    pageCount: 520,
    category: 'poetry',
    authorCountry: 'HU',
    source: 'manual',
    confidence: 1,
  },
];

/** ~34 books: Hungarian classics and translations, some with measured spine colours, long titles, no author, needs-review cases. */
export const SAMPLE_BOOKS: BookDTO[] = seeds.map((s) => makeSampleBook({ ...s, spineAuthor: s.author ?? null }));
